### ISSUE TITLE
Errno 2

### ISSUE THREAD

**Issue by jollyjuggler2** [enjoysmath/bootstrap-studio-to-django-template#3]
[https://imgur.com/a/3IwePxO](url) 
help me pls.

**Comment by enjoysmath** [comment]
Hi, @jollyjuggler2 You are the second person to want to use this.  The first person got busy with work for now.  I do have it up to date and working for my site.  Let me commit / push it to github.  The new instructions will simply call dev_bss_to_django.exe and all that does is call `python dev_bss_to_django.py`.  You could also accomplish with a batch file, but there is some other logic in that EXE file.    Anyway I'm just blabbing about Idk what.  Like I said, I will update the instructions today and you will have a working demo tonight / tomorrow!   Would you be willing to do a screenshare over Team Viewer, Zoom, MS Teams, or Google Meet  so that I can show you how to do thing with it?

**Comment by enjoysmath** [comment]
Yes, everything is up to date.  So if you follow the instructions on the Getting Started tab, but the EXE you point to should be dev_bss_to_django.exe (from BSS settings).  I would like to do a screen share with you at least over Google Meet, so that we can get you up and running.    Should problems persist, I made this software debuggable as it is called from BSS.  For that you'd need to download and install Wingware IDE.    But most likely we can get it to work without installing that.  So ping me any time here or at fruitful approach (one word) at google mail and we'll set up a meeting.
